### ISSUE TITLE
font.dat format + split APK

### ISSUE THREAD

**Issue by ghost** [bullbin/widebrim_hd#1]
Nice work so far! I had a few problems installing this since the latest version of the game seems to be stored as a split apk, which doesn't work with your setup script. I just had to copy the content from the InstallAssets apk, but there is no sound when I play and the game crashes when it tries to load the first puzzle. (Line 28 of gamemode_endpuzzle.gd)

I also have some info about the font.dat format, here goes.

uint32 num_characters
uint16 max_character_width
uint16 padding (probably)
uint16 atlas_width
uint16 atlas height

character table: uint16 character, uint16 cropped_width
After this is the actual atlas image, it's stored as 1 byte per pixel with alpha only. Hope that helps!

![laytonfontdat](https://github.com/bullbin/widebrim_hd/assets/166903181/d85679cf-ad80-48ea-8473-604478e5d7ae)

**Comment by bullbin** [comment]
Thanks, I noticed it was a 1bpc image with an alphabet but couldn't be bothered to go a step forward. It'll probably be some time before I get round to it but @creativelynameduser when this gets implemented, do you want to be added to credits section?

And yeah thanks for heads up, I forgot they migrated to split APKs in newer versions. I'll have to dump it again. I'm curious about the crash, I can't replicate it for v1.0.1. is there any error? There might be some differences in files (some important files were left same as NDS, may have been touched up) or missing altogether.

Audio is still a WIP, I'm still reversing the sound map which maps internal IDs to their filenames. For now the Python stuff just rips and converts the audio while pulling out looping metadata.

**Comment by ghost** [comment]
The error was that it couldn't find the file "gamemode_event.tscn", maybe you forgot to upload it to github? + it's fine if you credit me. Let me know if I can help with anything else

**Comment by bullbin** [comment]
I'm dumb, I broke earlier commits when I changed the pathing from last commit. No clue how I missed this, sorry. Should all be working as of newest commit c5cfeac, I'll add fonts (and split APK support) to the burner once I've got some more free time 👍

**Comment by bullbin** [comment]
As of commit 1b94926 font conversion is now a part of the asset extractor and I've added you to the credits list👍 I've tested it in-engine but that's not committed yet - I'll get around to converting nodes to use the new font. I've opened up a different issue for the split APK support so I'll close this one for now. Thanks for the help with font decoding ☺️
